from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
import logging
import asyncio
import os
import httpx

logger = logging.getLogger(__name__)
router = APIRouter()

class ActionSyncRequest(BaseModel):
    action_description: str
    owner: str = None
    priority: str = "medium"
    incident_id: str

@router.post("/jira/sync")
async def sync_to_jira(req: ActionSyncRequest):
    """Syncs an action item to Jira (uses real API if .env configured, otherwise mocks)."""
    logger.info("Syncing action to Jira: %s", req.action_description)
    
    jira_url = os.getenv("JIRA_DOMAIN")
    jira_email = os.getenv("JIRA_EMAIL")
    jira_api_token = os.getenv("JIRA_API_TOKEN")
    jira_project_key = os.getenv("JIRA_PROJECT_KEY", "SUT")
    
    if jira_url and jira_email and jira_api_token:
        try:
            async with httpx.AsyncClient() as client:
                auth = (jira_email, jira_api_token)
                payload = {
                    "fields": {
                        "project": {"key": jira_project_key},
                        "summary": req.action_description,
                        "description": f"Auto-generated by Sutradhar AI from incident {req.incident_id}\nOwner: {req.owner or 'Unassigned'}\nPriority: {req.priority}",
                        "issuetype": {"name": "Task"}
                    }
                }
                resp = await client.post(f"{jira_url}/rest/api/2/issue", json=payload, auth=auth, timeout=10.0)
                resp.raise_for_status()
                data = resp.json()
                return {"status": "success", "ticket_id": data["key"], "url": f"{jira_url}/browse/{data['key']}"}
        except Exception as e:
            logger.error("Jira API error: %s", e)
            raise HTTPException(status_code=500, detail=f"Jira Sync Failed: {str(e)}")
            
    # Mock fallback for hackathon demo
    await asyncio.sleep(0.5)
    import random
    ticket = f"{jira_project_key}-{random.randint(1000, 9999)}"
    return {"status": "success", "ticket_id": ticket, "url": f"https://jira.atlassian.com/browse/{ticket}"}

@router.post("/slack/notify")
async def notify_slack(req: ActionSyncRequest):
    """Syncs a notification to Slack (uses Webhook if configured, otherwise mocks)."""
    logger.info("Notifying Slack about action: %s", req.action_description)
    
    slack_webhook = os.getenv("SLACK_WEBHOOK_URL")
    if slack_webhook:
        try:
            async with httpx.AsyncClient() as client:
                payload = {
                    "text": f"🚨 *New Incident Action* ({req.incident_id})\n*Action:* {req.action_description}\n*Owner:* {req.owner or 'Unassigned'}\n*Priority:* {req.priority}"
                }
                resp = await client.post(slack_webhook, json=payload, timeout=5.0)
                resp.raise_for_status()
                return {"status": "success", "channel": "#incident-alerts"}
        except Exception as e:
            logger.error("Slack API error: %s", e)
            raise HTTPException(status_code=500, detail="Slack Sync Failed")
            
    await asyncio.sleep(0.2)
    return {"status": "success", "channel": "#incident-room"}
